import { NextResponse } from 'next/server';
import clientPromise from '@/lib/mongodb';
import { getCurrentUser } from '@/lib/auth';
import crypto from 'crypto';

// GET /api/mentor/invite - list active invite links/codes generated by this mentor
export async function GET() {
  try {
    const mentor = await getCurrentUser();
    if (!mentor || mentor.role !== 'mentor') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const client = await clientPromise;
    const db = client.db('aicoach_institutional');

    const invites = await db.collection('invitations')
      .find({ createdBy: mentor._id })
      .sort({ createdAt: -1 })
      .toArray();

    return NextResponse.json(invites);
  } catch (error) {
    console.error('Fetch Invites Error:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}

// POST /api/mentor/invite - generate a new invitation link and code
export async function POST(request: Request) {
  try {
    const mentor = await getCurrentUser();
    if (!mentor || mentor.role !== 'mentor') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json().catch(() => ({}));
    const { expiresDays = 30, maxUses = 100, degree, subject, year } = body;

    if (!degree || !subject || !year) {
      return NextResponse.json({ error: 'Degree, Subject, and Graduation Year are required' }, { status: 400 });
    }

    const client = await clientPromise;
    const db = client.db('aicoach_institutional');

    // Generate random 8 character string for code suffix (INST-XXXX-XXXX)
    const segment1 = crypto.randomBytes(2).toString('hex').toUpperCase();
    const segment2 = crypto.randomBytes(2).toString('hex').toUpperCase();
    const code = `INST-${segment1}-${segment2}`;

    const expiresAt = new Date();
    expiresAt.setDate(expiresAt.getDate() + expiresDays);

    const inviteDoc = {
      code,
      collegeName: mentor.collegeName,
      createdBy: mentor._id,
      createdAt: new Date(),
      expiresAt,
      maxUses: maxUses === null ? null : Number(maxUses),
      useCount: 0,
      status: 'active',
      degree,
      subject,
      year: Number(year)
    };

    await db.collection('invitations').insertOne(inviteDoc);

    return NextResponse.json({
      message: 'Invitation code created',
      code,
      link: `/signup?code=${code}`
    }, { status: 201 });
  } catch (error) {
    console.error('Generate Invite Error:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
