import type { Db, ObjectId } from 'mongodb';
import type { LLMGateway } from './llm-gateway';
import { validateWithShield } from './schema-shield';
import { buildNarrativePrompt } from './prompt-builder';
import { matchResources } from './resource-matcher';
import { dispatchReportReady, type Mailer } from './notifier';
import { getLLMGateway } from './llm-gateway';
import {
  createReportStub,
  findSession,
  updateReport,
  setReportStatusCache,
} from './session-store';
import { ReportNarrativeSchema } from './schemas';
import { compileStrengthsImprovements } from '../dashboard-suite/per-turn';
import type {
  CoachingReportDoc,
  QuestionEvaluation,
  Resource,
  TurnRecord,
} from './schemas';

/** The four CI categories aggregated from per-turn evaluations. */
export interface CategoryScores {
  technicalAccuracy: number;
  communication: number;
  voiceCi: number;
  bodyCi: number;
}

const WEAKNESS_THRESHOLD = 65;

const ZERO_CATEGORIES: CategoryScores = {
  technicalAccuracy: 0,
  communication: 0,
  voiceCi: 0,
  bodyCi: 0,
};

/**
 * Confidence Index, computed independently of narrative processing (Req 16.3):
 * `tech*0.35 + comm*0.25 + voice*0.20 + body*0.20`. The weights sum to 1, so for
 * inputs within 0..100 the result stays within 0..100, and when all four equal V
 * the result equals V.
 */
export function computeCiScore(c: CategoryScores): number {
  return (
    c.technicalAccuracy * 0.35 +
    c.communication * 0.25 +
    c.voiceCi * 0.2 +
    c.bodyCi * 0.2
  );
}

/**
 * Flag any category whose aggregated score is strictly below 65 (Req 17.1).
 * A score of exactly 65 is NOT flagged; a score of 0 IS flagged.
 */
export function weaknessTags(categoryScores: Record<string, number>): string[] {
  return Object.entries(categoryScores)
    .filter(([, score]) => score < WEAKNESS_THRESHOLD)
    .map(([category]) => category);
}

/**
 * Average the per-turn evaluation scores into category averages (Req 16.2).
 * Turns without a completed evaluation are skipped; with no evaluated turns the
 * aggregate is zero for every category (every category then flags as a weakness).
 */
export function aggregateCategoryScores(turns: TurnRecord[]): CategoryScores {
  const evals = turns
    .map((t) => t.evaluation)
    .filter((e): e is QuestionEvaluation => e != null);

  if (evals.length === 0) return { ...ZERO_CATEGORIES };

  const mean = (select: (e: QuestionEvaluation) => number): number =>
    evals.reduce((sum, e) => sum + select(e), 0) / evals.length;

  return {
    technicalAccuracy: Math.round(mean((e) => e.technicalAccuracy) * 1000) / 1000,
    communication: Math.round(mean((e) => e.communication) * 1000) / 1000,
    voiceCi: Math.round(mean((e) => e.voiceCi) * 1000) / 1000,
    bodyCi: Math.round(mean((e) => e.bodyCi) * 1000) / 1000,
  };
}

// No email infrastructure exists in the module yet; v1 uses a no-op mailer so the
// in-app notification is always created. Real email delivery is wired in later.
const noopMailer: Mailer = {
  async sendReportReady(): Promise<void> {},
};

/**
 * End-of-session report compilation (Req 16–20), intended to run inside `after()`.
 *
 * Aggregates turn metrics into category averages, computes the CI independently of
 * the narrative, flags sub-65 weakness tags, matches resources (institution-first,
 * ≤5), requests a narrative via LLM_Gateway + Schema_Shield, embeds the behavioral
 * timeline, and persists `coaching_reports`. The status is set to `ready` ONLY on
 * successful persistence; a persistence failure records `persistenceError` instead
 * (Req 16.4, 16.5). Notifications are dispatched only after a successful `ready`
 * persistence.
 */
export async function compileReport(
  db: Db,
  gateway: LLMGateway,
  sessionId: string,
  mailer: Mailer = noopMailer,
): Promise<void> {
  const session = await findSession(db, sessionId);
  if (!session) return;

  // Resolve the report stub: prefer the one linked at session end, otherwise create.
  let reportObjectId: ObjectId;
  if (session.reportId) {
    reportObjectId = session.reportId;
  } else {
    reportObjectId = await createReportStub(db, {
      sessionId: session._id,
      userId: session.userId,
    });
  }
  const reportId = reportObjectId.toString();

  // CI is computed independently of any narrative processing (Req 16.3).
  const categoryScores = aggregateCategoryScores(session.turns ?? []);
  const categoryRecord: Record<string, number> = { ...categoryScores };
  const ciScore = Math.round(computeCiScore(categoryScores) * 1000) / 1000;
  const tags = weaknessTags(categoryRecord);

  const { strengths, improvements } = compileStrengthsImprovements(session.turns ?? []);

  // Narrative and personalized dynamic recommendations generated by LLM (gemini, nvidia, etc.).
  let narrative: string | undefined;
  let resources: Resource[] = [];

  const narrativeResult = await validateWithShield(
    ReportNarrativeSchema,
    gateway,
    buildNarrativePrompt({
      ciScore,
      categoryScores: categoryRecord,
      weaknessTags: tags,
      strengths,
      improvements,
    }),
  );

  if (narrativeResult.ok) {
    narrative = narrativeResult.value.narrative;
    resources = (narrativeResult.value.recommendations || []).map((rec: any, idx: number) => ({
      id: `dyn_${idx}`,
      title: rec.title,
      url: rec.url,
      tags: [rec.weaknessTag],
      rationale: rec.rationale,
    }));
  } else {
    // Fallback: match resources from database if LLM recommendation fails
    const matched = await matchResources(db, tags, session.institutionCode);
    if (matched.ok) resources = matched.resources;
  }

  const patch: Partial<CoachingReportDoc> = {
    status: 'ready',
    ciScore,
    categoryScores,
    weaknessTags: tags,
    resources,
    behavioralTimeline: session.behavioralTimeline ?? [],
    readyAt: new Date(),
  };
  if (narrative !== undefined) patch.narrative = narrative;

  try {
    await updateReport(db, reportId, patch);
  } catch (err) {
    // Persistence failed after compilation: do NOT mark ready; record the failure.
    const message = err instanceof Error ? err.message : String(err);
    try {
      await updateReport(db, reportId, { status: 'failed', persistenceError: message });
      await setReportStatusCache(reportId, 'failed');
    } catch {
      // DB unavailable for the failure record too; nothing further we can persist.
    }
    return;
  }

  await setReportStatusCache(reportId, 'ready');

  // Notifications are dispatched only after a successful `ready` persistence.
  await dispatchReportReady(db, mailer, session.userId, reportObjectId);
}

/**
 * Convenience wrapper for the `after()` background hook: resolves the default
 * gateway (provider-agnostic) and compiles the report for the given session.
 */
export async function runReportJob(db: Db, sessionId: string): Promise<void> {
  await compileReport(db, getLLMGateway(), sessionId);
}
